### PR TITLE
Handle unexpected errors in file.Exists

### LINKED ISSUE #29: nil dereference in file.Exists
[file.Exists](https://github.com/anchore/grype-db/blob/main/internal/file/exists.go#L14) checks for `IsNotExist` errors, but does not handle unexpected errors. 

I was running grype as `nobody` in a `photon` container. $HOME defaults to /dev/null, so Grype was trying to look for `/dev/null/.cache`. os.Stat returns a `not a directory` error and `os.IsNotExist(err)` returns false. `info.IsDir` is a nil dereference and grype crashes.

Two options I can think of are:
1) return false if err != nil (the file being looked for is not usable for one reason or another)
- no interface change is needed, but grype's next step might be to create that file
2) return (false, err) so grype can print the error (so the user can update configuration appropriately) and terminate

### PR DESCRIPTION
**Pull request by xtreme-conor-nosal**
Fixes #29

Signed-off-by: Conor Nosal <cnosal@vmware.com>

### CODE REVIEW

File: pkg/curation/metadata_test.go [hunk 1]
```diff
@@ -10,43 +10,51 @@ import (
...
-			expected: Metadata{
+			expected: &Metadata{
 				Built:    time.Date(2020, 06, 15, 18, 02, 36, 0, time.UTC),
 				Version:  2,
 				Checksum: "sha256:dcd6a285c839a7c65939e20c251202912f64826be68609dfc6e48df7f853ddc8",
 			},
 		},
+		{
+			fixture:       "/dev/null/impossible",
+			expectedError: "unable to check if DB metadata path exists (/dev/null/impossible/metadata.json): stat /dev/null/impossible/metadata.json: not a directory",
```
Comment (wagoodman) [inline pkg/curation/metadata_test.go:35]: nit: mind checking the existence of an error instead of asserting the specific error text? The extra mile of asserting the specific text is noble but we also tend to avoid such checks since they are brittle to change. (when we run across cases like this in the code base that we think are really important to check against, we'll make sentinel errors and use `errors.Is` / `assert.ErrorIs` during checks).

Comment (xtreme-conor-nosal) [reply pkg/curation/metadata_test.go:35]: Sure. Do you want a sentinel error type in this case, or just the removal of expectedError string?

Comment (wagoodman) [reply pkg/curation/metadata_test.go:35]: I can't think of a specific reason why the caller would want to check this case specifically, so my vote would be on the simpler side --replace the string assertion with an existence check (assert we expect an error in this case, but comparing the error isn't necessary).

**Review by wagoodman — APPROVED** [review]
Looks great 💯
